language: node_js
branches:
  only:
    - master
    - dev
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn
  - yarn lint
  - yarn build
notifications:
  slack: uttnetgroup:dub9msi1fvNcpb1M5Wnmpuxo
deploy:
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: ua
    app: api-bouffe
    token: $OPENSHIFT_TOKEN
    on:
      branch: master
    edge: true
